### ISSUE TITLE
Theoretical mapping of EML to DCAT

### ISSUE THREAD

**Issue by peterdesmet** [oSoc15/ipt-dcat#1]
As we plan to use this mapping in the context of the IPT, I would not map the main EML standard, but the **EML GBIF profile** specifically. The mapping can be (first) described as a document (cf. [this document](https://code.google.com/p/gbif-providertoolkit/wiki/IPT2DataCiteMappings))

Question: what version of DCAT should we map to (Belgium, European, etc.)? It should work for the Flemish Open Data Platform and ideally all CKAN instances worldwide.

**Comment by pietercolpaert** [comment]
Trying to comply to dcat-ap seems the way to go. Dcat itself is very broad and doesn't require anything. Dcat Belgium at this moment is only a copy of dcat-ap, the European standard
