### ISSUE TITLE
Example for catalog dcat:themeTaxonomy

### ISSUE THREAD

**Issue by peterdesmet** [oSoc15/ipt-dcat#10]
Do you have an example for dcat:themeTaxonomy, so I have an idea of how this could be populated?

**Comment by pietercolpaert** [comment]
http://ns.thedatatank.com/dcat/themes :-)

**Comment by peterdesmet** [comment]
So http://eurovoc.europa.eu/5463 for `biodiversity`?

**Comment by pietercolpaert** [comment]
yes!

**Comment by peterdesmet** [comment]
Great, done in e2cab624d794f948b39981449b1dd2f56619e8ac
