### ISSUE TITLE
Can dataset dcat:keywords be grouped in sets?

### ISSUE THREAD

**Issue by peterdesmet** [oSoc15/ipt-dcat#11]
IPT keywords are grouped in thesauri. It would be useful to retain that information in DCAT, so that a harvester like the Flemish Open Data platform only imports keywords from a certain thesaurus (e.g. the one we specify with only Dutch keywords). Is there a way to express this in DCAT?

**Comment by pietercolpaert** [comment]
No. dcat:keyword literals are free strings, not tied to a thesaurus.

To tie something to a thesaurus, use dcat:theme

**Comment by peterdesmet** [comment]
OK, using theme and keywords now, which does not support the use case I mentioned above (only harvest keywords from a certain thesaurus). But we can't have everything. :smile:
