### ISSUE TITLE
How are dataset versions handled in DCAT

### ISSUE THREAD

**Issue by peterdesmet** [oSoc15/ipt-dcat#12]
The IPT supports versions, for both datasets and distributions (both have the same version number and increase it at the same time). Example:
- Dataset: http://data.inbo.be/ipt/resource?r=bird-tracking-gull-occurrences&v=5.1
- Distributions:
  - http://data.inbo.be/ipt/archive.do?r=bird-tracking-gull-occurrences&v=5.1
  - http://data.inbo.be/ipt/eml.do?r=bird-tracking-gull-occurrences&v=5.1
  - http://data.inbo.be/ipt/rtf.do?r=bird-tracking-gull-occurrences&v=5.1

A harvester, like GBIF or the Flemish Open Data platform, generally wants to update its entry of the dataset (e.g. updated title, description and version number) and distribution (replacing old one with new one and increasing version number).

What is the best way to express versions in DCAT?
- [x] By listing only the latest version of the dataset, with the latest distribution
- [ ] By listing only the latest version of the dataset, with all distribution versions
- [ ] By listing all versions of the dataset, each one with its own distribution

@pietercolpaert, you mentioned:

> Separate versions can be different resources which point to a generic dataset

What is then the title and description of the generic dataset? That of the latest version?

**Comment by pietercolpaert** [comment]
By creating new instances of a dcat:Dataset and link them together using these predicates:
- dct:hasVersion → links to dcat:Datasets which describe versions of the data
- dct:isVersionOf → reverse property of dct:hasVersion

Furthermore, more info can be given using `amds:versionNotes`, which is `a description of changes between this version and the previous version of the Asset.`

**Comment by peterdesmet** [comment]
We decided to **only list the latest versions of the datasets in the DCAT feed**. So an IPT with 11 resources (all with 1-10 versions) will have 11 datasets in the DCAT feed.

That also means we cannot support `dct:isVersionOf`, which expects a resource. We're dropping that optional term. We'll still populate `adms:versionInfo` and `adms:versionNotes`.
