### ISSUE TITLE
Best Distribution dcat:mediaType?

### ISSUE THREAD

**Issue by peterdesmet** [oSoc15/ipt-dcat#13]
If I understand mediaType, we could use the following for Darwin Core Archives:
- `zip`: understandable, but very general, less informative of what to expect
- `dwc-a`: less widely known, but gives good indication of what to expect

What do you suggest?

**Comment by pietercolpaert** [comment]
dcat:mediaType is the IANA defined string: https://www.iana.org/assignments/media-types/media-types.xhtml

dct:format can be whatever you'd like to add, such as dwc-a :)

**Comment by peterdesmet** [comment]
Can you check and expand on this commit: https://github.com/oSoc15/ipt-dcat/commit/9a8d895880d69b273839bdcce98294f212595e68 ?
