### ISSUE TITLE
Hash at end of URI might conflict with Angular

### ISSUE THREAD

**Issue by peterdesmet** [oSoc15/ipt-dcat#14]
@timrobertson100, care to expand?

**Comment by timrobertson100** [comment]
Many technologies are making use of the workarounds of anchors in the URL.  One is AngularJS, where the following is an example of an AngularJS URL (you can't see this, but just to illustrate the URL structure):
  http://registry.gbif.org/web/index.html#/dataset/f1d71f00-5da7-4f76-9149-b87b07a49ec1

It is highly likely that at some point (IPT 3.0+) the web layer of the IPT will be replaced, and it is _possible_ something like AngularJS might be used.  Building interoperability around URLs for webpages which are likely to change is probably fragile (i.e. going to be an issue in the future) and especially so if you make assumptions based around anchors on the pages which might be problematic in the future.

One option worth considering is a resource oriented architecture approach where you determine the entities you wish to link - e.g. a dataset.  Construct the linking URLs cleanly (e.g. www.myipt.org/api/resource1) and then have then redirect to the HTML representation / JSON / RDF etc as required.  By doing so you would not need to work around limitations of URL structures, remove possible conflict with web technologies and would have a layer of abstraction that would allow clean URLs.  Such an approach is more likely to be future proof, and easy to ensure is a maintained API.

It was just a thought, as the # workaround sounds like a potentially fragile hack.

**Comment by peterdesmet** [comment]
Pinging @pietercolpaert

**Comment by pietercolpaert** [comment]
The hash URI is mainly for machines and meta-data experts as an identifier. It should not be "clicked" by end-users of IPT.

I would still go with the hash for now
