### ISSUE TITLE
DCAT dataset dct:description is not the same as Eml#Description

### ISSUE THREAD

**Issue by simon-vc** [oSoc15/ipt-dcat#19]
[Eml#Description](https://github.com/gbif/ipt/blob/master/src/main/java/org/gbif/ipt/model/Ipt.java#L47) links to the description for the IPT if I'm correct
I suppose the description for a dataset is [Eml#Description](https://github.com/gbif/gbif-metadata-profile/blob/master/src/main/java/org/gbif/metadata/eml/Eml.java#L753)

Also, do I need to keep the paragraphs?

**Comment by peterdesmet** [comment]
Yes, I that was probably an incorrect link in my document. Dataset description = the resource abstract, with multiple paragraphs.
