### ISSUE TITLE
What organisation name should be used for the datacatalog?

### ISSUE THREAD

**Issue by simon-vc** [oSoc15/ipt-dcat#28]
The DCAT catalog needs to have a publisher.
Now both the IPT manager and the Organisation who publishes datasets have a name and can be different. (You can have multiple organisations)
Which name should we use for the publisher of the catalog?

**Comment by peterdesmet** [comment]
Yes, you can register multiple organizations in the same IPT. Is it feasible to express DCAT in hierarchical order by publisher? That would be the most robust solution for all uses of IPT. The list of registered organizations should be accessible somewhere in the code.

``` JSON
"publisher 1": {
    "catalog": {
        "dataset 1": { },
        "dataset 2": { }
    },
"publisher 2": { }
```

Pinging @kbraak

**Comment by kbraak** [comment]
To list all the IPT's associated organizations call:  https://github.com/gbif/ipt/blob/master/src/main/java/org/gbif/ipt/service/admin/RegistrationManager.java#L93 

I'm on vacation from today and won't be checking emails until 10 August. Good luck guys!

**Comment by peterdesmet** [comment]
After some discussion we decided to include a `dct:publisher` for each `dcat:Dataset`. This is also used in the [CKAN-DCAT mapping](https://github.com/ckan/ckanext-dcat/blob/master/README.md), so some harvesters should recognize this field.

For the `dct:publisher` of a `dcat:Catalog`, we'll follow the [definition](http://www.w3.org/TR/vocab-dcat/#Property:catalog_publisher):

> The entity responsible for making the catalog online.

Which fits well with the organization hosting the IPT, so let's use that. Hopefully harvesters will be smart enough to consider that the publisher of the catalog is not necessarily the publisher of each dataset.

The definition above and the fact that CKAN-DCAT is including a publisher for a dataset are the main reasons we decided agains having a catalog per publisher (see [my comment](https://github.com/oSoc15/ipt-dcat/issues/28#issuecomment-120475846) above), which is more complex.

I'll update the mapping file.

**Comment by peterdesmet** [comment]
One other advantage of doing it as such:
- `catalog#publisher` is mandatory, just as the IPT has to be registered with an organization, so we'll always have one
- `dataset#publisher` is optional, just as it is optional to register a resource with an organization in the IPT.

**Comment by peterdesmet** [comment]
As it's now updated in the mapping file, I'll close this issue.
