### ISSUE TITLE
Is the last modification the same as lastpublishdate?

### ISSUE THREAD

**Issue by simon-vc** [oSoc15/ipt-dcat#29]
In a dataset there is need for a dct:modified and in the mapping it explains this as date of last modification in the IPT.
Now, I suppose the last modification is the same as the publication date?

**Comment by coreation** [comment]
Make sure that when questions on github get answered (IRL, mail, slack, ....) to provide the answer here as well before closing the question. Just a pointer :).

**Comment by peterdesmet** [comment]
Yes, let's map `modified` to `lastPublished` (documented in a88ef84bf1a59c1bdecfc8803329931e3f61312c). IPT resources have a `lastModified` date as well, but the `lastPublished` increases together with the version number and is the more important date of the two.
