### ISSUE TITLE
Time format in DCAT?

### ISSUE THREAD

**Issue by simon-vc** [oSoc15/ipt-dcat#30]
The Date class used in the IPT to define a date is deprecated. A DCAT date needs to be formatted in the [ISO8601](http://www.w3.org/TR/NOTE-datetime) standard. This is only supported since Java 8.
Should I parse the deprecated class Date or can I convert to the Java 8 standard?

**Comment by peterdesmet** [comment]
I'll let @timrobertson100 answer this question.

**Comment by timrobertson100** [comment]
The IPT needs to run on Java 6
