### ISSUE TITLE
How to define the spatial data?

### ISSUE THREAD

**Issue by simon-vc** [oSoc15/ipt-dcat#31]
There has to be a resource for the spatial data in a dataset. The IPT defines two points with a longitude and latitude.

My thoughts:

```
dct:spatial [ geo:point [ geo:lat "65" ; geo: long "36" ] ; geo:point [ geo:lat "34" ; geo: long "15" ] ]
```

**Comment by peterdesmet** [comment]
The current expression is just two points. It's better to express a bounding box or polygon representing the bounding box. After some discussion, @coreation noticed [DCAT allows to express this information as geojson](https://ies-svn.jrc.ec.europa.eu/projects/metadata/wiki/INSPIRE_profile_of_DCAT-AP_-_Reference#Geographic-bounding-box), which is widely recognized. I'll figure out the mapping.

**Comment by peterdesmet** [comment]
From the [polygon example](http://geojson.org/geojson-spec.html#id4):

``` JSON
{
  "type": "Polygon",
  "coordinates": [
    [ [minLong, minLat], [minLong, maxLat], [maxLong, maxLat], [maxLong, minLat], [minLong, minLat] ]
  ]
}
```

## Example
- minLat:10
- minLong: -25
- maxLat: 60
- maxLong: 10

``` JSON
{
  "type": "Polygon",
  "coordinates": [
    [ [-25, 10], [-25, 60], [10, 60], [10, 10], [-25, 10] ]
  ]
}
```

You can of course express this on one line:

``` JSON
{ "type": "Polygon", "coordinates": [ [ [-25, 10], [-25, 60], [10, 60], [10, 10], [-25, 10] ] ] }
```

You can test the output in [Geojsonlint](http://geojsonlint.com/).

**Comment by peterdesmet** [comment]
For the `catalog:spatial`, we propose to also use geojson, but this time as a point:

``` JSON
{
    "type": "Point",
    "coordinates": [
        longitude,
        latitude
    ]
}
```

``` JSON
{ "type": "Point", "coordinates": [ 4.334187, 50.842133 ] }
```
