### ISSUE TITLE
Dataset modified

### ISSUE THREAD

**Issue by peterdesmet** [oSoc15/ipt-dcat#34]
DCAT Dataset title, description, keywords, contacts, etc. will be those as currently populated in the IPT, not those of the last published version of a resource (I need to actually verify this). For Dataset `modified` date however, we'll use the `last publication date`, as it is a more important date, which increases with the version number. That means however that some elements (title, description, keywords, etc.) might change without the `modified` date to change.

@timrobertson100, knowing this, would you suggest to map to `last modified date` instead of `last published date`?

**Comment by timrobertson100** [comment]
Last published date is when the last archive was published - that would be the timestamp the distribution was made
A last modified date... not entirely sure what you would use that for in the context of DCAT...

**Comment by peterdesmet** [comment]
The date the metadata of the resource was updated?

**Comment by timrobertson100** [comment]
Seems sensible.
