### ISSUE TITLE
Error messages on every screen

### ISSUE THREAD

**Issue by peterdesmet** [oSoc15/ipt-dcat#38]
I'm testing the IPT-DCAT on our development server and I get green error/warning messages on every screen (e.g. while editing metadata):

![screen shot 2015-07-28 at 14 25 51](https://cloud.githubusercontent.com/assets/600993/8931214/d5bc476c-3534-11e5-9099-b312cb628aa5.png)

Is there as certain setting causing this or are those errors valid?

**Comment by Amenai** [comment]
Those logs comes from theTesting/debugging IPT program , not our fault normally .
