### ISSUE TITLE
Struts problem on dcat feed

### ISSUE THREAD

**Issue by peterdesmet** [oSoc15/ipt-dcat#39]
When I want to access the dcat feed on the IPT I am testing, I get this:

![screen shot 2015-07-28 at 14 29 04](https://cloud.githubusercontent.com/assets/600993/8931251/0b078184-3535-11e5-995e-20598276837a.png)

Any idea how to prevent this?

**Comment by Amenai** [comment]
We have forgot to test with a "non-published resource". We need the last published date for every resource in the DCAT. We just change our list with all of the resource by a list with all of the published resource. Nice testing , we just fix it.

**Comment by peterdesmet** [comment]
Can you email me a new .war file, so I can retest? Thanks!

**Comment by simon-vc** [comment]
the file is too big to send through email

**Comment by peterdesmet** [comment]
Can you temporarely host it on Dropbox or Google Drive and email me the link?

**Comment by simon-vc** [comment]
I put the file in my google drive and send a mail

**Comment by peterdesmet** [comment]
Problem is fixed. Thanks.
