### ISSUE TITLE
Odd whitespace and punctuation in dcat feed

### ISSUE THREAD

**Issue by peterdesmet** [oSoc15/ipt-dcat#41]
Setup: a test IPT registered with a test organization. No published datasets.

The dcat feed has some `.` or `;` at the end of each lines. Is this valid? And if required, wouldn't it be better to remove the whitespace before? E.g. `@prefix schema: <http://schema.org/> .` -> `@prefix schema: <http://schema.org/>.`?

```
@prefix adms: <http://www.w3.org/ns/adms#> .
@prefix schema: <http://schema.org/> .
@prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#> .
@prefix dcat: <http://www.w3.org/ns/dcat#> .
@prefix foaf: <http://xmlns.com/foaf/0.1/> .
@prefix dct: <http://purl.org/dc/terms/> .
@prefix xsd: <http://www.w3.org/2001/XMLSchema#> .
@prefix locn: <http://www.w3.org/ns/locn#> .
@prefix skos: <http://www.w3.org/2004/02/skos/core#> .
@prefix vcard: <http://www.w3.org/2006/vcard/ns#> .

<http://.../ipt-dcat/#catalog>
 a dcat:Catalog ;
dct:title "IPT DCAT" ;
dct:description "IPT DCAT" ;
dct:publisher <http://www.gbif.org/publisher/b2069a2e-0fb3-4193-9fee-1910694cfca5/#Organization> ;
dct:issued "2015-07-29T09:19+02:00" ;
dct:modified "2015-07-29T09:19+02:00" ;
dcat:themeTaxonomy <http://eurovoc.europa.eu/218403> ;
dct:rights <https://creativecommons.org/publicdomain/zero/1.0/> .

<http://eurovoc.europa.eu/218403> a skos:ConceptScheme ; dct:title "biodiversity"@en .

<http://www.gbif.org/publisher/b2069a2e-0fb3-4193-9fee-1910694cfca5/#Organization> a foaf:Agent ; foaf:name "IPT DCAT" .
```

**Comment by simon-vc** [comment]
The dcat feed is written in turtle syntax. There need to be spaces before the `.` and `;`
`.` is used to define the end of a triple
`;` defines the seperation between predicates (e.g. dct:title)
`,` is used to seperate between objects (the value for the predicate)

**Comment by peterdesmet** [comment]
OK. Is the DCAT validator already running somewhere?

**Comment by Amenai** [comment]
http://validator.dcat.be/ !

**Comment by peterdesmet** [comment]
Thanks. I noticed that the turtle expression of the [Datatank Demo](http://demo.thedatatank.com/api/dcat) has the same whitespace. The validator seems to allow no whitespace (maybe something to report?)

**Comment by peterdesmet** [comment]
@simon-vc, I assume that `;`, not `,` is used to separate objects in [your comment](https://github.com/oSoc15/ipt-dcat/issues/41#issuecomment-125889593)?

**Comment by Amenai** [comment]
We dont understand, can you give us the error message or the DCAT feed. We test a lots of time and we didn't get this error

**Comment by peterdesmet** [comment]
Sorry, should have been clearer:
- This issue can be closed (whitespace is required)
- The validator does NOT complain if there is NO whitespace (this is a validator issue)

**Comment by Amenai** [comment]
They use a library to check and validate the code, they cant change it for the moment. Thx for the report
