### ISSUE TITLE
Timestamp in DCAT feed is off by an hour

### ISSUE THREAD

**Issue by peterdesmet** [oSoc15/ipt-dcat#42]
Setup: a test IPT registered with a test organization. No published datasets.

If I generate the DCAT feed on 11:01 GMT+2, the timestamp in the feed is 10:01 GMT+2. Is this an error in the code or is something wrong on the server I'm using?

```
dct:issued "2015-07-29T10:01+02:00" ;
dct:modified "2015-07-29T10:01+02:00" ;
```

**Comment by simon-vc** [comment]
Issued is the first time a publication was published in the catalog
Modified is the last date of a publication in the catalog

I'm trying to fix the problem when there are no resources published

**Comment by peterdesmet** [comment]
The hour difference is probably a server error: all hours listed on that IPT are off by one hour.
