### ISSUE TITLE
Dataset mandatory according to validator

### ISSUE THREAD

**Issue by peterdesmet** [oSoc15/ipt-dcat#43]
Setup: a test IPT registered with a test organization. **No published datasets**.

If I paste the DCAT feed into the [validator](http://validator.dcat.be/), I get one error:

> The property: dataset is mandatory

So, if there are no published datasets, should we generate a feed at all?

**Comment by simon-vc** [comment]
Good question, I suppose not. I'll just return a blank that says there are no published datasets.

**Comment by peterdesmet** [comment]
Can you have comments in DCAT? If so, I would generate `No published datasets.` as a comment, so it still validates as DCAT.

**Comment by simon-vc** [comment]
it would be a valid turtle file, but not a valid dcat
still it will be better in comments

**Comment by pietercolpaert** [comment]
A catalog with no datasets should still be published I believe as usual... The fact that when there are no datasets it doesn't validate shouldn't be too much of a problem ;)

**Comment by peterdesmet** [comment]
Ok, let's keep the useful information then. @pietercolpaert Isn't it a bit odd that datasets are required then by DCAT-AP?

**Comment by peterdesmet** [comment]
Confirmed fixed in `v1.2`
