### ISSUE TITLE
Incorrect publisher for Catalog

### ISSUE THREAD

**Issue by peterdesmet** [oSoc15/ipt-dcat#46]
GBIF registers organizations (e.g. INBO) and IPT installations (e.g. the INBO IPT).

In the DCAT feed, the catalog has a publisher. This is currently mapped to the IPT installation (`IPT DCAT` in my test), not the organization (or organizations!) using that installation as a publisher (`INBO`). I think it should be the latter.

```
<http://.../ipt-dcat/#catalog>
 a dcat:Catalog ;
dct:title "IPT DCAT" ;
dct:description "IPT DCAT" ;
dct:publisher <http://www.gbif.org/publisher/b2069a2e-0fb3-4193-9fee-1910694cfca5/#Organization> ;
dct:issued "2015-07-29T12:26+02:00" ;
dct:modified "2015-07-29T12:26+02:00" ;
dcat:themeTaxonomy <http://eurovoc.europa.eu/218403> ;
dct:rights <https://creativecommons.org/publicdomain/zero/1.0/> ;
dct:spatial [ a dct:Location ; locn:geometry "{ \"type\": \"Point\", \"coordinates\": [ 3.49,51.2 ] }" ] .

<http://eurovoc.europa.eu/218403> a skos:ConceptScheme ; dct:title "biodiversity"@en .

<http://www.gbif.org/publisher/b2069a2e-0fb3-4193-9fee-1910694cfca5/#Organization> a foaf:Agent ; foaf:name "IPT DCAT" .


```

Note 1: The URL http://www.gbif.org/publisher/b2069a2e-0fb3-4193-9fee-1910694cfca5 won't return anything, because those are test environment UUIDs.

Note 2: the URL of the registered IPT installation (i.e. the catalog) might be useful information. @pietercolpaert, is there another term we can use for this?

**Comment by peterdesmet** [comment]
@pietercolpaert, on Note 2: `dct:identifier` is probably a good term (cf. dataset).

**Comment by Amenai** [comment]
Every IPT installation need to be register in GBIF. So the link will be a link to the organisation register in GBIF ,so the organisation hosting the IPT ( INBO ). But in test mode the first organisation you create is the owner of the IPT.

**Comment by peterdesmet** [comment]
Agreed, but the publisher currently listed is:

```
<http://www.gbif.org/publisher/b2069a2e-0fb3-4193-9fee-1910694cfca5/#Organization> a foaf:Agent ; foaf:name "IPT DCAT" .
```

Which is the IPT installation itself, not the organization(s). It should be:

```
<http://www.gbif.org/publisher/0a16da09-7719-40de-8d4f-56a15ed52fb6/#Organization> a foaf:Agent ; foaf:name "Test Organisation #1" .
```

**Comment by simon-vc** [comment]
There was some confusing between the IPT and the Hosting Organisation
This is fixed now and changed in the mapping file

**Comment by peterdesmet** [comment]
Confirmed fixed in `v1.2`: shows the organization.

Question: if multiple organizations are linked to the IPT, which one will be listed as publisher?

**Comment by simon-vc** [comment]
The publisher of the catalog is the one hosting it
The rest will be mentioned as publishers of the datatsets

**Comment by peterdesmet** [comment]
So it uses the GBIF registry to find out the organization hosting the IPT? That's cool! Is this a relation that is readily available in the IPT?

**Comment by simon-vc** [comment]
The IPT knows the hosting organisation
