### ISSUE TITLE
Multiple contactPoints not valid according to validator

### ISSUE THREAD

**Issue by peterdesmet** [oSoc15/ipt-dcat#54]
A DCAT feed with multiple contactPoints for a dataset now returns an error in the validator: `The property: contactPoint can't have multiple objects`:

```
dcat:contactPoint [ a vcard:Individual ; vcard:fn "Eric Stienen"  ; vcard:hasEmail <mailto:eric.stienen@inbo.be> ] ;
dcat:contactPoint [ a vcard:Individual ; vcard:fn "Peter Desmet"  ; vcard:hasEmail <mailto:peter.desmet@inbo.be> ] ;
```

Side remark: there's a double space before the `;`

@pietercolpaert probably a validator issue?

**Comment by simon-vc** [comment]
The validator hasn't been updated yet.
In the current version it will show this error and a warning that the schemes aren't there.
