### ISSUE TITLE
Organization homepage is dummy value

### ISSUE THREAD

**Issue by peterdesmet** [oSoc15/ipt-dcat#55]
The organization homepage is a dummy value in `v1.2`. It should not be listed if there is no homepage for the organization.

```
<http://www.gbif.org/publisher/0a16da09-7719-40de-8d4f-56a15ed52fb6#Organization> a foaf:Agent ; foaf:name "Test Organisation #1" ; foaf:homepage <[http://homepage.com]> .
```

Question: where would organization homepage get its value from (in the code)?

Remark: use http://example.com for dummy domain names, it is set up for just that. http://homepage.com is a real estate website. :smile:

**Comment by simon-vc** [comment]
This is not in the code, this refers to this: http://www.gbif-uat.org/publisher/0a16da09-7719-40de-8d4f-56a15ed52fb6

There it states that the homepage is http://homepage.com

**Comment by peterdesmet** [comment]
Ah cool, my mistake. :-)
