### ISSUE TITLE
Verify dct:identifier type

### ISSUE THREAD

**Issue by kbraak** [oSoc15/ipt-dcat#56]
Referring to the [DCAT to IPT mappings](https://github.com/oSoc15/ipt-dcat/blob/master/mapping.md), can you please verify dct:identifier is supposed to be type literal, and not type resource?

**Comment by peterdesmet** [comment]
@pietercolpaert might know: is `dct:identifier` supposed to be a literal?

**Comment by pietercolpaert** [comment]
Yes, should be a literal

**Comment by pietercolpaert** [comment]
Also see http://dublincore.org/documents/dcmi-terms/#terms-identifier → has range Literal :-)

**Comment by kbraak** [comment]
Thanks - you can't argue with the documentation :) 

Can I suggest using the dataest DOI as the primary value for dct:identifier, defaulting to the GBIF UUID if none exists? 

Take http://ipt.gbif-uat.org/resource?r=testdelor , which has been assigned DOI but isn't registered with GBIF. The value for dct:identifier could be "http://doi.org/10.15469/bnyean".

**Comment by peterdesmet** [comment]
Where can the DOI identifier be found in the IPT code?

**Comment by kbraak** [comment]
DOI is an attribute of the Resources, and stored as part of each VersionHistory entry. 

Please be aware the IPT only mints DOIs for datasets when it is configured with a DataCite or EZID account. 

When the IPT registers a dataset with GBIF, GBIF will assigns it a DOI. The IPT doesn't show the GBIF assigned DOI however. There is an open issue to do this in the future though, see https://github.com/gbif/ipt/issues/1151

**Comment by peterdesmet** [comment]
Would it be OK to pick up this feature when https://github.com/gbif/ipt/issues/1151 has been implemented?

**Comment by kbraak** [comment]
Sounds like a good idea, let's open a separate issue for that. In the meantime, I'd really appreciate your guys' help testing the DCAT feed.
