### ISSUE TITLE
Complete list of DCAT-AP properties

### ISSUE THREAD

**Issue by peterdesmet** [oSoc15/ipt-dcat#6]
The [mapping](https://github.com/LifeWatchINBO/ipt-dcat/blob/master/mapping.md) currently contains the mandatory properties. @pietercolpaert, can you complete this with optional (useful) ones? No rush.

**Comment by pietercolpaert** [comment]
Added the mandatory fields. There are a lot of optional fields that are low hanging fruit still to be added. To be done when the code is written?

**Comment by peterdesmet** [comment]
Yep. Thanks for the input!
