### ISSUE TITLE
Decide on URIs for Publisher, Catalog, Dataset, and Distribution

### ISSUE THREAD

**Issue by peterdesmet** [oSoc15/ipt-dcat#7]
The current proposal for the URIs is:
- Publisher: not yet decided
- Catalog: http://data.inbo.be/ipt#Catalog
- Dataset: http://data.inbo.be/ipt/resource?r=bird-tracking-gull-occurrences#Dataset
- Distribution: http://data.inbo.be/ipt/archive?r=bird-tracking-gull-occurrences

I'd like to let @timrobertson100 from GBIF weigh in on the possibility of having even nicer URIs provided by the IPT, e.g. with content negotiation.

(see also #5)

**Comment by peterdesmet** [comment]
@timrobertson100 @pietercolpaert @coreation can I close this issue?

**Comment by timrobertson100** [comment]
Sorry, I don't really understand the proposal.
The IPT URLs are likely to be embedded in many places by now, so think it would be unwise to do significant changes to them.  It looks like you aren't though...

**Comment by pietercolpaert** [comment]
Indeed, we aren't. What we're doing is disambiguating the identifier for "the page about a certain organisation" and "the organisation" itself. The page about the organisation should mention the URI somehow though as being its primary topic

**Comment by peterdesmet** [comment]
Closing this issue.
