### ISSUE TITLE
What is catalog foaf:homepage?

### ISSUE THREAD

**Issue by peterdesmet** [oSoc15/ipt-dcat#8]
Is this the homepage of the catalog, or rather publisher or dataset?

**Comment by pietercolpaert** [comment]
As an example: the home page of the catalog of the Flemish government is http://data.opendataforum.info

Does that answer your questions?

**Comment by peterdesmet** [comment]
OK, so the (home)page of the catalog (i.e. overview of datasets). For an IPT, that is the IPT homepage.
