### ISSUE TITLE
What is catalog dct:rights

### ISSUE THREAD

**Issue by peterdesmet** [oSoc15/ipt-dcat#9]
Is this the license of the catalog list itself or the license of all datasets (which might be different for each dataset)?

**Comment by pietercolpaert** [comment]
depends on which subject this applies. If dct:rights is added on the dcat:Catalog, it's the catalog...

**Comment by peterdesmet** [comment]
I see it is required for distributions, is it advised to have this for all objects?

**Comment by pietercolpaert** [comment]
On the dcat:Catalog I would add a CC0 by default

I would advice to have it on all distributions indeed

**Comment by peterdesmet** [comment]
- Catalog now uses CC0 (static value)
- Distributions get it from the IPT

@pietercolpaert: what about datasets: is it often applied there as well?

**Comment by pietercolpaert** [comment]
nope, a dct:rights is only added to the distribution itself. This makes sense: data itself cannot be copyrighted, but the container of the data can. Therefor a license should be added on the distribution :)

**Comment by peterdesmet** [comment]
OK. You could argue that the dataset metadata can be licensed, which is stored at the `dataset` concept, but I'm fine with having it at catalog and distribution only.

**Comment by pietercolpaert** [comment]
the license of the metadata is already given for the entire catalog in the dcat:Catalog URI
